on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run integration tests
        uses: ./.github/actions/vscode-test

      - name: Lint
        run: npm run lint
